[package]
name = "rust-todo-app"
version = "0.1.0"
authors = ["Jodhandeep Singh <49287012+jdsingh122918@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
